Add Gaussian blur as first take
But it is really really bad for performance. Actually one simple frame
being processed almost for 900 milliseconds, which is really long and

    Error: "Internal data stream error."

happens...

How to fix it - IDK yet.